#!/bin/sh
BASEDIR=$(dirname "$0")

source $BASEDIR/functions.sh

source $BASEDIR/exports.sh

source $BASEDIR/alias.sh

export PATH=$PATH:$BASEDIR/utils

#Auto completion for zsh
fpath=($BASEDIR/completions $fpath)
